# Generated by Django 6.0.3 on 2026-04-04 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangBo',
            fields=[
                ('DangBoID', models.AutoField(primary_key=True, serialize=False)),
                ('TenDangBo', models.CharField(max_length=255)),
                ('CapDangBo', models.CharField(max_length=100)),
                ('TrangThai', models.CharField(default='Đang hoạt động', max_length=50)),
            ],
            options={
                'db_table': 'DangBo',
            },
        ),
        migrations.CreateModel(
            name='ChiBo',
            fields=[
                ('ChiBoID', models.AutoField(primary_key=True, serialize=False)),
                ('TenChiBo', models.CharField(max_length=255)),
                ('DiaBan', models.CharField(max_length=255)),
                ('TrangThai', models.CharField(max_length=50)),
                ('DangBoID', models.ForeignKey(db_column='DangBoID', on_delete=django.db.models.deletion.PROTECT, to='qldv.dangbo')),
            ],
            options={
                'db_table': 'ChiBo',
            },
        ),
        migrations.CreateModel(
            name='DangVien',
            fields=[
                ('DangVienID', models.AutoField(primary_key=True, serialize=False)),
                ('SoCCCD', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('MaDangVien', models.CharField(blank=True, max_length=50, unique=True)),
                ('HoTen', models.CharField(max_length=255)),
                ('BiDanh', models.CharField(blank=True, max_length=255, null=True)),
                ('GioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10)),
                ('NgaySinh', models.DateField()),
                ('QueQuan', models.CharField(blank=True, max_length=255, null=True)),
                ('NoiThuongTru', models.CharField(blank=True, max_length=255, null=True)),
                ('NoiTamTru', models.CharField(blank=True, max_length=255, null=True)),
                ('DanToc', models.CharField(blank=True, max_length=100, null=True)),
                ('NgheNghiep', models.CharField(blank=True, max_length=255, null=True)),
                ('GDPT', models.CharField(blank=True, max_length=100, null=True)),
                ('GDNN', models.CharField(blank=True, max_length=255, null=True)),
                ('GDDH', models.CharField(blank=True, max_length=255, null=True)),
                ('GDSĐH', models.CharField(blank=True, max_length=255, null=True)),
                ('HocHam', models.CharField(blank=True, max_length=100, null=True)),
                ('LyLuanChinhTri', models.CharField(blank=True, max_length=255, null=True)),
                ('NgoaiNgu', models.CharField(blank=True, max_length=255, null=True)),
                ('TinHoc', models.CharField(blank=True, max_length=255, null=True)),
                ('TiengDTTS', models.CharField(blank=True, max_length=255, null=True)),
                ('NgayVaoDang', models.DateField()),
                ('NgayChinhThuc', models.DateField(blank=True, null=True)),
                ('TrangThaiSinhHoat', models.CharField(choices=[('Đang sinh hoạt', 'Đang sinh hoạt'), ('Chuyển sinh hoạt', 'Chuyển sinh hoạt'), ('Nghỉ', 'Nghỉ')], default='Đang sinh hoạt', max_length=50)),
                ('DienDangVien', models.CharField(choices=[('DU_BI', 'Dự bị'), ('CHO_XET', 'Chờ xét'), ('CHINH_THUC', 'Chính thức'), ('BI_XOA_TEN', 'Bị xóa tên')], default='DU_BI', max_length=20)),
                ('SoDienThoai', models.CharField(blank=True, max_length=10, null=True)),
                ('DiaChi', models.CharField(max_length=255)),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('ChiBoID', models.ForeignKey(db_column='ChiBoID', on_delete=django.db.models.deletion.PROTECT, to='qldv.chibo')),
                ('DangBoID', models.ForeignKey(db_column='DangBoID', on_delete=django.db.models.deletion.PROTECT, to='qldv.dangbo')),
            ],
            options={
                'db_table': 'DangVien',
            },
        ),
        migrations.CreateModel(
            name='HuyHieuDang',
            fields=[
                ('HuyHieuID', models.AutoField(primary_key=True, serialize=False)),
                ('LoaiHuyHieu', models.CharField(max_length=255)),
                ('NgayDuDieuKien', models.DateField()),
                ('DotTraoTang', models.CharField(max_length=50)),
                ('TrangThai', models.CharField(max_length=50)),
                ('SoQuyetDinh', models.CharField(max_length=50)),
                ('NgayTrao', models.DateField()),
                ('GhiChu', models.TextField(blank=True, null=True)),
                ('DangVienID', models.ForeignKey(db_column='DangVienID', on_delete=django.db.models.deletion.CASCADE, to='qldv.dangvien')),
            ],
            options={
                'db_table': 'HuyHieuDang',
            },
        ),
    ]
