# Generated by Django 6.0.4 on 2026-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldv', '0002_alter_dangvien_ngayvaodang'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangvien',
            name='HuyHieuCaoNhat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
