# Generated by Django 6.0.4 on 2026-04-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qldv', '0003_dangvien_huyhieucaonhat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangvien',
            name='DiaChi',
        ),
    ]
