# Generated by Django 6.0.4 on 2026-04-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qldv', '0004_remove_dangvien_diachi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangvien',
            name='SoHuyHieu',
            field=models.IntegerField(default=0),
        ),
    ]
